language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  username: __token__
  password:
    secure: NorTXQMS2b/9Ra7F1xKe38d7ys52PSagrTM/ysCVbxlPDJ8974J/F7ZTVHvhu0wkd1bBb+C9e48s/ppbs+njunutNdg7cRfY7YawEnFadJ8NKw++9LQ1ML1r7JRRz9QTdlrKsEuO9QNZVEjokXKbnsu4AbyKgcDmgmW6yyeoZzbtwDu3bt/hmE4NBN4BduYoPp3urZKZLCk7I3rQf73e2anx+gGl3koklQj+5lqaZWdkHyEMFj5FS0jMJysXrALdwULQRhF4fqdKGfumCJPrrb0s7WxIluqs94DWtC682fycoxA6LpHCJoEmEtYNzYxzelwaHOpCEo28gUZHV/Q+m3+S9dtAmi/8I0+xGPgmd1gyQWZAVPI20UMmb9HFIDNIYdsag9qd01MkqHSg+/qP9IwJELO3qLA8MWm6P8jG81Rz1J15cVdOd1Toyuuu+znOxlNFUqduNS5iTELQOtnxTTNHZQ+Ci9d18MKnxAGbZi7eqkrBSDG2JHYigz42HiMLLWWgI4B3AtnRSgc/zXS+YtBjkJBI2LGcB0wi3WPyVg4IK3WX/WiQJyuGvSxEeN2bnf+BSwq5/0zltmZX/S9yAio9/XcZq7m8RAuMk1vm0y85487BfcY1RU5VqIO6/hfjqQmAMgGB7toi7npg69nPdalmITVx447Yhxc2UiLeWsg=
  on:
    tags: true
    repo: mondrian-scwgs/csverve
    python: 3.8
