version: 0.2

env:
  variables:
    PYPI_TOKEN: $PYPI_TOKEN
phases:
  pre_build:
    commands:
  build:
    commands:
      - pip install -r requirements_dev.txt && pytest
      - mypy csverve
  post_build:
    commands:
      - if [ $CODEBUILD_BUILD_SUCCEEDING = 1 ]; then python setup.py sdist bdist_wheel && twine upload --skip-existing -u __token__ -p $PYPI_TOKEN dist/*; fi
